
AllCops:
  TargetRubyVersion: 2.4

# This is *temporary*; when we fix it, remember to update Reek config as well.
Style/Documentation:
  Exclude:
    - apps/**/*.rb
    - lib/bookshelf.rb
    - spec/features_helper.rb

# This is also *temporary*; Real Code&trade; sources should include the comment.
Style/FrozenStringLiteralComment:
  Enabled: false

# It's likely that we'll eventually broaden this to include *all* specs.
Metrics/BlockLength:
  Exclude:
    - apps/web/application.rb
    - spec/**/*.rb
